### ISSUE TITLE
[Hacktoberfest]: Update Content for Web Directions Summit

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#100]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:
The README for this project has some repeat/placeholder comments. If you look at the look at the Readme you will see resources, articles, webpages, videos etc that have the same generic comment to describe them. We'd like the specific information to replace those placeholder texts

📋 Step by Step
Step by Step

🙋 Claim this issue by commenting on it.
* Create a New Branch How to branch, Commit, Pull, Merge - start at step2
* Make your change - I use Github Desktop and Visual Studio Code so I don't have to do anything via the command-line, but if you like the command-line git on with it ;-)
* The change I suggest is go to the Conferences Table, starts around line 164. Edit the Web Directions Summit line so that it reads:

`| [Web Directions Summits](https://www.webdirections.org/) | Web Directions | 10 | A conference for the whole team |`

* Commit it Make it a good one
* Make a Pull Request Tell us what you did
* We'll review it and merge it in
* Add yourself as a Contributor to the bottom of the Readme.md using the same formatting as the others in the list

Remember to observe the Code of Conduct - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by aortiz24** [comment]
@msandfor, I would like to work on this! It's my first time at hacktoberfest!

**Comment by codess-aus** [comment]
Go ahead and make your PR - tell me if you need any help :-)

**Comment by codess-aus** [comment]
@aortiz24 - here is an additional step-by-step tutorial in case you need it - just amend the content from this issue instead of the content change from the tutorial:

https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md

**Comment by aortiz24** [comment]
I have completed all my pull request!

**Comment by codess-aus** [comment]
closed PR #131  Congrats @aortiz24
