### ISSUE TITLE
[Hacktoberfest]: Add Dylan Beattie to the Mentors Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#107]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

Add content to this list:

Add Dylan Beattie to the line below the last line in step 4, Follow some Mentors section. Ensure a space remains after you insert your entry:

📋 Step by Step
**Step by Step**

* Click on the Readme.MD and then click on the little pen (top right) to edit the file
* Add this line to the line below the last line in step 4, Follow some Mentors section. Ensure a space remains after you insert your entry:

`| [Dylan Beattie](https://dylanbeattie.net/) | Ursatile | 4 | Creator of the [Rockstar](https://codewithrockstar.com/) programming language, a Microsoft MVP for Visual Studio and Development Technologies |`

*Commit your change Make it a good one
* Make a Pull Request Tell us what you did
* We'll review it and merge it in
* Add yourself as a Contributor to the bottom of the Readme.md using the same formatting as the others in the list

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by Jayant0jha** [comment]
Hey @msandfor , can I work on this?

**Comment by codess-aus** [comment]
Hey @Jayant0jha - not this one, because you already worked on an easy one. You have to go to the next level now. Look at issues #28 or #29 and either investigate a resource that has only placeholder text in the info, and see if you can replace that with info from their website to summarise them better. Or, if you know of a good resource/mentor - add them in.

i.e. - This issue has a cut and paste of the contribution to be made. But issues #28 and #29 ask you to think a bit about the input and add something in that way. Try one of those.

**Comment by Arvind25R** [comment]
Can I work on this ? @msandfor I have recently started using github. It would be helpful for me to get into open source by doing this.

**Comment by codess-aus** [comment]
Sure, go ahead

**Comment by codess-aus** [comment]
resolved by PR #119
