### ISSUE TITLE
[Hacktoberfest]: Add Eddie Jaoude Community to the Get Involved Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#118]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:
Add content to this list: Eddie Jaoude Community

📋 Step by Step

* 🙋 Claim the issue by commenting on it.
* [Step-by-Step](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)
* For the edit - go down to the *Get Involved* section that starts around line 103 and add this beneath the last entry in the table, ensuring there is still a blank line before the next section starts

`| [Eddie Jaoude Community](https://eddiejaoudecommunity.github.io/) | Eddie Jaoude | 5 | OPEN SOURCE is NOT about code, it is about people and collaboration |'

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by Retnuh1337** [comment]
I'll take this

**Comment by codess-aus** [comment]
Closed PR #132
