### ISSUE TITLE
[Hacktoberfest]: Add Diana Rodriguez to Mentors Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#122]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Add Diana Rodriguez to the Mentors section
* See below for link to step-by-step tutorial
* Go down to Mentors section - it starts at around line 83
* Paste the following information underneath the last row in the table, ensuring there is still an empty row before the next table.

`| [alphacentauri82](https://github.com/alphacentauri82) | Diana Rodriguez | 4 | Python Developer Advocate @ Vonage, GDE: web/cloud/maps/firebase,  Microsoft MVP, Auth0 Ambassador |` 

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by amiecroteau** [comment]
I'll take this issue

**Comment by codess-aus** [comment]
Closed PR #130
