### ISSUE TITLE
[Hacktoberfest]: Add "QCon New York" to the Conferences Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#141]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Add *QCon New York* to the Conferences Section
* See below for link to step-by-step tutorial
* Go down to Conferences section - it starts at around line 173
* Using the following template, put in the correct info for that conference (Search for it on the internet to find the correct details) underneath the last row in the table, ensuring there is still an empty row before the next table.

`| [Conference Name](Website Address) | Conference Name or Organising Org | 10 | Description of the Conferences, found on their website |` 

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by mamadou-diallo** [comment]
I can take care of this :)

**Comment by mamadou-diallo** [comment]
PR #277 has been left for this issue :)
