### ISSUE TITLE
[Hacktoberfest]: Add Open Source Guide to Step 11

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#160]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Add [Open Source Guides](https://opensource.guide/) to the *And Then What?* Section / Step 11
* See below for link to step-by-step tutorial
* Go down to <example> section - it starts at around line <line number>
  * Copy paste the info below into the correct table.

`| [Open Source Guides](https://opensource.guide/) | GitHub and Friends | 11 | Open source software is made by people just like you. Learn how to launch and grow your project |` 

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by RemcoHalman** [comment]
I would like to take this. Love the open source vibe

**Comment by codess-aus** [comment]
Have at it 👍

**Comment by codess-aus** [comment]
Good Job @RemcoHalman Closed with PR #165
