### ISSUE TITLE
[Hacktoberfest]: Edit Phil Nash in Twitch Stream Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#178]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Edit [Phil Nash](https://www.twitch.tv/phil_nash/) in the Twitch Section
* See below for link to step-by-step tutorial
* Go down to Twitch section - it starts at around line 167
 
Update the Phil Nash entry to read:

`| [Phil Nash](https://www.twitch.tv/phil_nash) | Twilio | 9 | Developer evangelist for Twilio and a Ruby and JavaScript developer |` 

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by dhnv08** [comment]
Hello, May I take this?

**Comment by codess-aus** [comment]
Go right ahead @xvidviii

**Comment by codess-aus** [comment]
Resolved in PR #191
