### ISSUE TITLE
[Hacktoberfest]: Edit the Clarkio entry in the Twitch Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#181]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Edit Clarkio in the Twitch Section
* See below for link to step-by-step tutorial
* Go down to Twitch section - it starts at around line 167
 
Update the entry to read:

`| [Clarkio](https://www.twitch.tv/clarkio) | Microsoft | 9 | Streams about NodeJS, VS Code, and Fart Noises. It's a very High-brow stream, so put on your finest clothes and mind your manners |`

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by dhnv08** [comment]
Hello, I want to work this issue

**Comment by codess-aus** [comment]
You can only take one issue @xvidviii - others want to make their first PRs during Hacktoberfest

**Comment by dhnv08** [comment]
Okay, thank you
