### ISSUE TITLE
[Hacktoberfest]: Edit Pair Programming Entry in the Twitch Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#183]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Edit *Pair Programming* entry in the Twitch Section
* See below for link to step-by-step tutorial
* Go down to Twitch section - it starts at around line 167
 
Update the entry to read:

`| Pair Programming ](https://www.twitch.tv/jlengstorf) | Jason Lengstorf | 9 | Jason Lengstorf hosts Learn With Jason, a pair programming livestream where we learn something new in 90 minutes! |`

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by wanjuntham** [comment]
May I take up on this please?

**Comment by codess-aus** [comment]
Closed by PR #216
