### ISSUE TITLE
[Hacktoberfest]: Edit the Coding tips, tricks, and techniques entry in the Twitch Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#185]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Edit *Coding tips, tricks, and techniques* entry in the Twitch Section
* See below for link to step-by-step tutorial
* Go down to Twitch section - it starts at around line 167
 
Update the entry to read:

`| [Coding tips, tricks, and techniques ](https://www.twitch.tv/brianlagunas/) | Brian Lagunas | 9 | Microsoft MVP, a Xamarin MVP, a Microsoft Patterns & Practices Champion, co-leader of the Boise .Net Developers User Group (NETDUG), board member of Boise Code Camp, speaker, trainer, and Pluralsight author |`

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by OtchereDev** [comment]
I will take this

**Comment by codess-aus** [comment]
Still working on this @OtchereDev  ?

**Comment by OtchereDev** [comment]
I am done with please.... The pull request has been merged already for this
