### ISSUE TITLE
[Hacktoberfest]: Edit the CodingGarden entry in the Twitch section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#187]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Edit *CodingGarden* entry in the Twitch Section
* See below for link to step-by-step tutorial
* Go down to Twitch section - it starts at around line 167
 
Update the entry to read:

`| [Learn with CodingGarden](https://www.twitch.tv/codinggarden) | CodingGarden | 9 | Open, interactive and engaging community where any coder, from beginner to veteran, can learn and grow together |`

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by Zualemo-xo** [comment]
Ill take this?
