### ISSUE TITLE
[Hacktoberfest]: Update Content in the Chael Codes entry for Twitch

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#188]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Edit *Chael Codes* entry in the Twitch Section
* See below for link to step-by-step tutorial
* Go down to Twitch section - it starts at around line 167
 
Update the entry to read:

`| [Chael Codes](https://www.twitch.tv/chaelcodes) | Chael Codes | 9 |  Fun and engaging ways to code |`

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by f1ypopper** [comment]
Can I work on this issue?

**Comment by codess-aus** [comment]
Closed with PR#189
