### ISSUE TITLE
[Hacktoberfest]: Edit entry for Layla Codesit in the Twitch Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#189]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Edit *Layla Codesit* entry in the Twitch Section
* See below for link to step-by-step tutorial
* Go down to Twitch section - it starts at around line 167
 
Update the entry to read:

`| [Layla Codesit](https://www.twitch.tv/laylacodesit) | Twilio | 9 | Self-taught .NET developer, Microsoft MVP, Twilio Developer Evangelist |'

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by f1ypopper** [comment]
I can handle this issue!

**Comment by codess-aus** [comment]
You can only take one issue @Atharva8 - others want to make their first PR during Hacktoberfest

**Comment by codess-aus** [comment]
Closed
