### ISSUE TITLE
[Hacktoberfest]: Edit entry for Microsoft Developer in the Twitch Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#190]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Edit *Microsoft Developer* entry in the Twitch Section
* See below for link to step-by-step tutorial
* Go down to Twitch section - it starts at around line 167
 
Update the entry to read:

`| [Microsoft Developer](https://www.twitch.tv/microsoftdeveloper/) | Microsoft Developer | 9 | A humble group of developers and technical enthusiasts within Microsoft who operate this Twitch channel devoted to including you into the conversations we have |`

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by f1ypopper** [comment]
Please assign me this issue

**Comment by codess-aus** [comment]
You can only take one issue @Atharva8 - others want to make their first PR during hacktoberfest

**Comment by voidxyzvoidxyz** [comment]
I will take this
