### ISSUE TITLE
[Hacktoberfest]: Add Tatiana Mac to the Mentors Section 

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#198]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 Please only take one issue each. Others want to contribute to Hacktoberfest and my fingers hurt from creating so many issues.

To do:

* Add Tatiana Mac to the Mentors Section
* See below for link to step-by-step tutorial
* Go down to Mentors section - it starts at around line 91
  * Using the following template, paste info for that resource underneath the last row in the table, ensuring there is still an empty row before the next table.

`| [Tatiana Mac](https://codepen.io/tatianamac/) | Tatiana Mac | 4 | Tech Misanthropologist. Engineer/OSS maintainer |` 

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by OtchereDev** [comment]
I will take this
