### ISSUE TITLE
[Hacktoberfest]: Add STEM Stories to the YouTube Vids Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#206]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Add STEM Stories to the YouTube Vid Section
* See below for link to step-by-step tutorial
* Go down to YouTube section - it starts at around line 160
  * Using the following template, paste in the correct info for that resource underneath the last row in the table, ensuring there is still an empty row before the next table.

`| [STEM Stories](https://www.youtube.com/playlist?list=PLfj0ilPGpPyEMI7kCtjOnTOiQs8nAf1L1) | Colt Steele | 8 | Video Stories from Women Working in STEM Careers |` 

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by Mithunitp** [comment]
I'll take this
