### ISSUE TITLE
[Hacktoberfest]: Add - The Case of the Missing Method to the YouTube Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#210]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Add *The Case of the Missing Method* in the YouTube Section
* See below for link to step-by-step tutorial
* Go down to YouTube section - it starts at around line 160
 
Update the entry to read:

`| The Case of the Missing Method ](https://youtu.be/mn2D_k-X-es) | Nadia Odunayo | 8 | A Ruby Mystery Story at RubyConf |`

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by SondreWang** [comment]
I'll take this!

**Comment by AutumnWishes87** [comment]
I'll take this
