### ISSUE TITLE
[Hacktoberfest]: Add RubyConf to the Conferences Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#212]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Add *RubyConf* to the Conferences Section
* See below for link to step-by-step tutorial
* Go down to Conferences section - it starts at around line 173
* Paste the following code underneath the last row in the table, ensuring there is still an empty row before the next table.

`| [RubyConf](https://rubyconf.org/) | Ruby Central Org | 10 | RubyConf is the world’s largest and longest-running gathering of Ruby enthusiasts, practitioners, and companies |` 

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by laadysufiia** [comment]
I'll take this

**Comment by codess-aus** [comment]
Hi @diisophiia - just noticed that you made the change in your own fork and merged it to your own master branch, but have not merged it to  my master repo. If you look at the top of your code screen, there is an option for you to make a PR to me

![image](https://user-images.githubusercontent.com/5952956/95407464-acbbfe80-094f-11eb-9810-05efa22b3e05.png)

**Comment by laadysufiia** [comment]
Ohh I see, I'll fix it now :)

**Comment by codess-aus** [comment]
Good job
