### ISSUE TITLE
[Hacktoberfest]: Add RubyGems to the And Then What? Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#213]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Add *RubyGems* to the *And then what?* Section
* See below for link to step-by-step tutorial
* Go down to *And then what* section - it starts at around line 218
* Paste the following code underneath the last row in the table, ensuring there is still an empty row before the next table.

`| [RubyGems s](https://guides.rubygems.org/)) | RubyGems.org | 11 | RubyGems.org is the Ruby community’s gem hosting service |`

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by kezizhou** [comment]
I'll take this

**Comment by codess-aus** [comment]
Closed with PR #219
