### ISSUE TITLE
[Hacktoberfest]: Add Design Portfolio Workflow to the And Then What Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#214]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Add *Design Portfolio Workflow* to the *And Then What?* Section
* See below for link to step-by-step tutorial
* Go down to section - it starts at around line 217
* Paste the correct info for that resource underneath the last row in the table, ensuring there is still an empty row before the next table.

`| [Design Portfolio Workflow ](https://medium.com/@katfukui/the-design-portfolio-workflow-a94030d0b39e) |kat fukui
 | 11 | A complete guide to code and deploy a site, all from the terminal |` 

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by Shweta200126** [comment]
@msandfor 
I'll take this , I am new , just did my first pr for a readme file (dont know how it really went , I hope it helped.) 
can u link the 'And then what' section pls

**Comment by codess-aus** [comment]
@Shweta200126  if you follow the Step-by-step tutorial linked in the issue, it will show you, step-by-step, what to do. You are just clicking on the pen icon to edit the README and pasting the text in grey into the table near the bottom of the README - you'll find it at around line 217 in the Readme.

**Comment by Shweta200126** [comment]
@msandfor I did it , hope it helped. bookmaked this page , its an useful resource. thx.

**Comment by codess-aus** [comment]
Hope you clicked the Star on the Repo as well @Shweta200126

**Comment by codess-aus** [comment]
Congrats on your merge
