### ISSUE TITLE
[Hacktoberfest]: Add Responsive Web Design to the Podcast Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#226]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Add Responsive Web Design to the Podcast Section
* See below for link to step-by-step tutorial
* Paste the below line underneath the last row in the podcast table, ensuring there is still an empty row before the next table.

`| Responsive Web Design ](https://responsivewebdesign.com/podcast/) | Karen McGrane and Ethan Marcotte | 7 | Karen and Ethan interview the people who make responsive redesigns happen |` 

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by ghost** [comment]
I'll take this
