### ISSUE TITLE
[Hacktoberfest]: Add StyleGuides Podcast

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#228]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Add The Style Guides Podcast to the Podcast Section
* See below for link to step-by-step tutorial
* Paste the below line underneath the last row in the podcast table, ensuring there is still an empty row before the next table.

`| TheStyle Guides Podcast ](http://styleguides.io/podcast/) |  Anna Debenham and Brad Frost. | 7 | A small batch series of interviews on Style Guides |` 

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by wanjuntham** [comment]
May I take this?

**Comment by wanjuntham** [comment]
Please assign it to me if I can work on this.

**Comment by codess-aus** [comment]
Hey @wanjuntham - just a heads-up:
The reason the link is not displaying properly is because you are missing the opening square bracket at the start of the line -

![image](https://user-images.githubusercontent.com/5952956/95682749-99dc4f00-0c19-11eb-9f72-9df3af886557.png)

Also - don't forget, if you want that to contribute to the main Repo (not just your fork), you'll need to make a pull request:

![image](https://user-images.githubusercontent.com/5952956/95682807-fb042280-0c19-11eb-94ed-2716b21b4aae.png)
