### ISSUE TITLE
[Hacktoberfest]:Edit Scott Hanselman in the Mentors section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#234]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Edit Scott Hanselman in the Resources Section
* See below for link to step-by-step tutorial
* Go down to mentors section 
 * Change the placeholder description of *Be Kind* to:

*Scott Hanselman is a programmer, teacher, speaker, technologist, podcaster, writer, diversity advocate and more*

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by ehizman** [comment]
I will take this
