### ISSUE TITLE
[Hacktoberfest]: Edit the Humans of IT comment in the Get Involved Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#240]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

Go down to the **Get Involved** Section
Edit the **Humans of IT** entry, so that the comment says **Empowering technologists to achieve more by humanizing tech**

`| [Resource Name](Website Address) | Resource Name or Organising Org | Step Number | Description of the Resources, found on their website |` 

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by panditita** [comment]
I'll take this if that's ok 😊
