### ISSUE TITLE
[Hacktoberfest]:Edit Codenewbie in Podcasts Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#254]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Edit CodeNewbie comments in Podcast section to say **Stories from people on their coding journey**
* See below for link to step-by-step tutorial

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by iamhabee** [comment]
i will like to take this issue

**Comment by codess-aus** [comment]
Sorry @iamhabee looking at the page, it seems that one has already been done too. Why don't you take this one: Issue #225 

https://github.com/msandfor/10-Easy-Steps/issues/225
