### ISSUE TITLE
[Hacktoberfest]: Add Quantum Katas to the And Then What? Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#264]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

*Add **Quantum Katas** to the **And Then What?** Section
* See below for link to step-by-step tutorial
* Go down to **And Then What?** section - it's the last table in the README.MD
* Paste the below details underneath the last row in the table, ensuring there is still an empty row before the next table.

`| [Quantum Katas](https://github.com/Microsoft/QuantumKatas/#run-online) | Microsoft | 11 | The Quantum Katas are a collection of self-paced tutorials and programming exercises to help you learn quantum computing and Q# programming |` 

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by ravenblack24** [comment]
I'll take this one please!
