### ISSUE TITLE
[Hacktoberfest]: Add Python for Beginners to the YouTube Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#265]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Add Python for Beginners to the YouTube Section
* See below for link to step-by-step tutorial  
* Using the following template, put in the correct info for that resource (Search for it on the internet to find the correct details) underneath the last row in the table, ensuring there is still an empty row before the next table.

`| [Python for Beginners](https://www.youtube.com/playlist?list=PLlrxD0HtieHhS8VzuMCfQD4uJ9yne1mE6) | Microsoft Developer | 8 | The foundation for programming in Python, starting from common everyday code and scenarios |` 

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by RizosKonstantinos** [comment]
I'll take this
