### ISSUE TITLE
[Hacktoberfest]: Add Javascript for Beginners to the YouTube Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#266]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Add Javascript for Beginners to the YouTube Section
* See below for link to step-by-step tutorial  
* Using the following template, put in the correct info for that resource (Search for it on the internet to find the correct details) underneath the last row in the table, ensuring there is still an empty row before the next table.

`| [Javascript for Beginners](https://www.youtube.com/playlist?list=PLlrxD0HtieHhW0NCG7M536uHGOtJ95Ut2) | Microsoft Developer | 8 | A series of videos to focus on the core concepts of JavaScript |` 

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by 0zymandias11** [comment]
hey, i will take this

**Comment by acristinabg** [comment]
I´ll take this.

**Comment by codess-aus** [comment]
@Cristinabg854 you said you'd take this 4 hours ago, but @Flamer17 said they'd take it 18 hours ago. Have to give them a chance to do it first

**Comment by acristinabg** [comment]
Ok. I understood @msandfor

**Comment by codess-aus** [comment]
pick another @Cristinabg854 - there are plenty

**Comment by codess-aus** [comment]
PR #276
