### ISSUE TITLE
[Hacktoberfest]: Add Jennifer Wadella to the Mentors Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#301]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Add Jennifer Wadella to the Mentors Section
* See below for link to step-by-step tutorial

Here are some details about her you can use to make the entry, copy the format of other entries in the table:

Jennifer Wadella @likeOMGitsFEDAY
**Force of nature. JS dev. Tech speaker. Angry Feminist Harpy. Foodie. #kcnative. Mastermind behind: 
@KCWomeninTech  @CoderDojoKC  @CodeCocktailsKC @CodeCupcakeskc**

* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by darkresq14** [comment]
I'll take this
