### ISSUE TITLE
[Hacktoberfest]: Update Jessica Chan in the Mentors Section

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#304]
🆕🐥☝ Beginners Only:
This issue is reserved for people who are new to Open Source. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

To do:

* Edit the **Jessica Chan** entry in the **Mentors** Section, so the comments are amended to read **Sharing experiences and knowledge that can help others on their coding journey** to replace the placeholder comment *Be Kind*
* Add your details in the contributors section at the bottom of the page using the same formatting as the last one

📋 *Step by Step*
[Step-By-Step Tutorial](https://github.com/msandfor/10-Easy-Steps/blob/master/docs/GitHub-browser-tutorial.md)

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by ch1771dr0b0** [comment]
I'll take this.
