### ISSUE TITLE
[Bug]: Broken Links in emoji-key.md

### ISSUE THREAD

**Issue by Keatnuxsuo** [msandfor/10-Easy-Steps#52]
**Describe the bug**
The links redirect to 404 page 

**To Reproduce**
1. Go to '10-Easy-Steps/docs/emoji-key.md'
3. Scroll down to 'What's next'
4. Click on 'Notes for repository maintainers' and 'Automating the process using tools'

**Expected behavior**
Clicking on these links lead to a 404 page

**Screenshots**
![image](https://user-images.githubusercontent.com/24486796/94560423-3d7e4480-0295-11eb-8fef-fee7f902e212.png)

**Desktop (please complete the following information):**
 - Browser: Microsoft Edge 
 - Version: Version 85.0.564.63

**Comment by ghost** [comment]
Hey @Keatnuxsuo can I work on this issue (I could not understand the issue)? Do I have to modify the redirect links. If so, to what?

**Comment by Keatnuxsuo** [comment]
@premkiran7 of course! I'm just not sure what is the right path for these links. Thank you!

**Comment by codess-aus** [comment]
Hi @Keatnuxsuo thanks for raising this issue, let's look at it during our 1-2-1 tomorrow and you can show me what you did and what you expected. @premkiran7 If I find this is an unexpected behaviour, I will clarify the Issue for you with steps to fix and you can work on it. Watch this space ⌚ 👀

**Comment by codess-aus** [comment]
Hi @premkiran7 - to fix this issue, could you please:
1. Go to '10-Easy-Steps/docs/emoji-key.md'
2. Click on Edit This File
3. Delete all text from Line 9

'Table
To have a contribution added when using the Bot or CLI use the keyword in the Type column. The bot will also use basic Natural Language Parsing to determine your contribution intent.'

4. Delete all text from Line 45 until end of File
' What's next
Notes for repository maintainers
Automating the process using tools'

5. Commit Changes and make a Pull Request. I will merge the PR tomorrow (1st Oct).

6. Please also follow instructions in the [Contributing.MD](https://github.com/msandfor/10-Easy-Steps/blob/master/contributing.md) where it tells you how to Add yourself to the list of contributors

**Comment by codess-aus** [comment]
Thanks @premkiran7 
@all-contributors please add @premkiran7  for bug doc 🚧
