### ISSUE TITLE
[Hacktoberfest]: Update Content to YOW Conferences

### ISSUE THREAD

**Issue by codess-aus** [msandfor/10-Easy-Steps#95]
To do:
The README for this project has some repeat/placeholder comments. If you look at the look at the Readme you will see resources, articles, webpages, videos etc that have the same generic comment to describe them. We'd like the specific information to replace those placeholder texts

📋 Step by Step
**Step by Step**
* 🙋 Claim this issue by commenting on it.
* Create a New Branch [How to branch, Commit, Pull, Merge - start at step2](https://guides.github.com/activities/hello-world/)
* Make your change - I use [Github Desktop](https://desktop.github.com/) and [Visual Studio Code](https://code.visualstudio.com/) so I don't have to do anything via the command-line, but if you like the command-line git on with it ;-)

The change I suggest is go to the Conferences Table, starts around line 164. Edit the YOW Conferences line so that it reads:

`| [YOW Conferences](https://yowconference.com/) | YOW | 10 | Emerging technologies and best practices in the software industry |`

* Commit it [Make it a good one](https://dev.to/chrissiemhrk/git-commit-message-5e21)
* Make a Pull Request [Tell us what you did](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)
* We'll review it and merge it in
* Add yourself as a Contributor to the bottom of the Readme.md using the same formatting as the others in the list

Remember to observe the [Code of Conduct](https://github.com/msandfor/10-Easy-Steps/blob/master/code_of_conduct.md) - by which we mean, in short - Be Kind, Be Positive, Be Helpful

**Comment by aortiz24** [comment]
I would like to work on this! It's my first time at hacktoberfest!

**Comment by newbietestuser** [comment]
I'll take this

**Comment by codess-aus** [comment]
Sure go ahead

**Comment by codess-aus** [comment]
Closed with PR #114
